/* FURKAN KAYA - DESIGN RUNTIME */
(function(){
  "use strict";
  if(!document.querySelector(".site-header")) return;
  const client=window.supabaseClient;
  const D={
    color_gold:"#f2ad16",color_gold_light:"#ffd35a",color_gold_dark:"#9a6307",color_black:"#030405",color_dark:"#07090b",color_dark_card:"#0d1013",color_dark_card_2:"#12161a",color_white:"#f4f4f4",color_text:"#e8e8e8",color_muted:"#8b9198",container_width:1280,side_padding:40,header_height:82,logo_font_size:21,logo_gap:7,nav_gap:40,nav_font_size:14,header_button_width:132,header_button_height:48,header_button_radius:6,header_button_font_size:13,hero_gap:80,hero_content_max_width:700,hero_content_padding_top:70,hero_content_padding_bottom:110,hero_small_font_size:11,hero_small_letter_spacing:6,hero_title_font_size:100,hero_title_line_height:.98,hero_title_letter_spacing:-5,hero_description_font_size:17,hero_description_max_width:560,hero_description_line_height:1.8,hero_buttons_gap:16,hero_button_height:58,hero_button_padding:25,hero_button_gap:25,hero_button_radius:6,hero_button_font_size:13,hero_gold_glow_size:500,brand_letter_1:"F",brand_letter_2:"K",brand_name:"REKLAM",brand_font_size:330,brand_gap:10,brand_letter_spacing:-30,brand_name_font_size:70,brand_name_letter_spacing:18,brand_name_margin_top:30,brand_line_width:70,brand_line_height:2,brand_line_margin_top:38,brand_glow_size:480,brand_glow_blur:15,section_padding:115,section_heading_gap:60,section_heading_margin_bottom:55,section_title_font_size:64,section_title_letter_spacing:-2,portfolio_columns:4,portfolio_columns_tablet:2,portfolio_gap:20,portfolio_radius:10,portfolio_image_height:245,portfolio_info_padding:20,slider_arrow_size:48,about_gap:100,about_text_font_size:16,about_text_line_height:1.9,services_gap:20,service_card_padding:35,service_card_radius:12,service_icon_size:70,service_card_min_height:200,service_card_gap:25,service_columns:3,contact_padding:60,contact_gap:60,contact_radius:14,contact_link_height:140,contact_link_padding:28,contact_section_padding:120,contact_title_font_size:58,contact_text_font_size:14,footer_padding:32,mobile_hero_gap:0,mobile_header_height:82,mobile_side_padding:20,mobile_hero_title_size:52,mobile_hero_title_size_small:52,mobile_hero_description_size:14,mobile_hero_description_size_small:14,mobile_hero_visual_height:330,mobile_hero_padding_top:100,mobile_hero_padding_bottom:20,mobile_brand_size:180,mobile_brand_spacing:-18,mobile_brand_name_size:35,mobile_brand_name_spacing:9,mobile_section_padding:80,mobile_portfolio_image_height:300,mobile_portfolio_image_height_small:240,mobile_contact_padding:25,mobile_button_height:58,mobile_button_gap:16
  };
  const px=v=>typeof v==="number"?v+"px":v;
  const parse=v=>typeof v==="string"&&/^-?\d+(\.\d+)?$/.test(v.trim())?Number(v):v;
  let current={...D};
  function set(doc,s,p,v){doc.querySelectorAll(s).forEach(e=>e.style.setProperty(p,v,"important"));}
  function apply(s){
    current={...D,...s}; const doc=document, r=doc.documentElement;
    const a=(q)=>doc.querySelector(q);
    r.style.setProperty("--gold",current.color_gold);r.style.setProperty("--gold-light",current.color_gold_light);r.style.setProperty("--gold-dark",current.color_gold_dark);r.style.setProperty("--black",current.color_black);r.style.setProperty("--dark",current.color_dark);r.style.setProperty("--dark-card",current.color_dark_card);r.style.setProperty("--dark-card-2",current.color_dark_card_2);r.style.setProperty("--white",current.color_white);r.style.setProperty("--text",current.color_text);r.style.setProperty("--muted",current.color_muted);r.style.setProperty("--container",px(current.container_width));
    if(a(".brand-f"))a(".brand-f").textContent=current.brand_letter_1;if(a(".brand-k"))a(".brand-k").textContent=current.brand_letter_2;if(a(".hero-brand-name"))a(".hero-brand-name").textContent=current.brand_name;
    set(doc,".site-header","height",px(current.header_height));set(doc,".header-container,.section-container,.footer-container,.hero-container","width","min("+px(current.container_width)+", calc(100% - "+px(current.side_padding*2)+"))");set(doc,".site-logo","font-size",px(current.logo_font_size));set(doc,".site-logo","gap",px(current.logo_gap));set(doc,".main-nav","gap",px(current.nav_gap));set(doc,".nav-link","font-size",px(current.nav_font_size));set(doc,".header-contact-button","width",px(current.header_button_width));set(doc,".header-contact-button","height",px(current.header_button_height));set(doc,".header-contact-button","border-radius",px(current.header_button_radius));set(doc,".header-contact-button","font-size",px(current.header_button_font_size));
    set(doc,".hero-container","gap",px(current.hero_gap));set(doc,".hero-content","max-width",px(current.hero_content_max_width));set(doc,".hero-content","padding",px(current.hero_content_padding_top)+" 0 "+px(current.hero_content_padding_bottom));set(doc,".hero-small-text","font-size",px(current.hero_small_font_size));set(doc,".hero-small-text","letter-spacing",px(current.hero_small_letter_spacing));set(doc,".hero-title","font-size",px(current.hero_title_font_size));set(doc,".hero-title","line-height",current.hero_title_line_height);set(doc,".hero-title","letter-spacing",px(current.hero_title_letter_spacing));set(doc,".hero-description","font-size",px(current.hero_description_font_size));set(doc,".hero-description","max-width",px(current.hero_description_max_width));set(doc,".hero-description","line-height",current.hero_description_line_height);set(doc,".hero-buttons","gap",px(current.hero_buttons_gap));set(doc,".primary-button,.secondary-button","height",px(current.hero_button_height));set(doc,".primary-button,.secondary-button","padding-left",px(current.hero_button_padding));set(doc,".primary-button,.secondary-button","padding-right",px(current.hero_button_padding));set(doc,".primary-button,.secondary-button","gap",px(current.hero_button_gap));set(doc,".primary-button,.secondary-button","border-radius",px(current.hero_button_radius));set(doc,".primary-button,.secondary-button","font-size",px(current.hero_button_font_size));set(doc,".hero-gold-glow","width",px(current.hero_gold_glow_size));set(doc,".hero-gold-glow","height",px(current.hero_gold_glow_size));
    set(doc,".hero-brand-main","font-size",px(current.brand_font_size));set(doc,".hero-brand-main","gap",px(current.brand_gap));set(doc,".hero-brand-main","letter-spacing",px(current.brand_letter_spacing));set(doc,".hero-brand-name","font-size",px(current.brand_name_font_size));set(doc,".hero-brand-name","letter-spacing",px(current.brand_name_letter_spacing));set(doc,".hero-brand-name","margin-top",px(current.brand_name_margin_top));set(doc,".brand-line","width",current.brand_line_width+"%");set(doc,".brand-line","height",px(current.brand_line_height));set(doc,".brand-line","margin-top",px(current.brand_line_margin_top));set(doc,".brand-glow","width",px(current.brand_glow_size));set(doc,".brand-glow","height",px(current.brand_glow_size));set(doc,".brand-glow","filter","blur("+px(current.brand_glow_blur)+")");
    set(doc,".portfolio-section,.about-section,.services-section","padding-top",px(current.section_padding));set(doc,".portfolio-section,.about-section,.services-section","padding-bottom",px(current.section_padding));set(doc,".section-heading","gap",px(current.section_heading_gap));set(doc,".section-heading","margin-bottom",px(current.section_heading_margin_bottom));set(doc,".section-heading h2","font-size",px(current.section_title_font_size));set(doc,".section-heading h2","letter-spacing",px(current.section_title_letter_spacing));set(doc,".portfolio-slider","grid-template-columns","repeat("+current.portfolio_columns+",1fr)");set(doc,".portfolio-slider","gap",px(current.portfolio_gap));set(doc,".portfolio-card","border-radius",px(current.portfolio_radius));set(doc,".portfolio-image","height",px(current.portfolio_image_height));set(doc,".portfolio-info","padding",px(current.portfolio_info_padding));set(doc,".slider-arrow","width",px(current.slider_arrow_size));set(doc,".slider-arrow","height",px(current.slider_arrow_size));set(doc,".about-grid","gap",px(current.about_gap));set(doc,".about-content p","font-size",px(current.about_text_font_size));set(doc,".about-content p","line-height",current.about_text_line_height);set(doc,".services-grid","gap",px(current.services_gap));set(doc,".services-grid","grid-template-columns","repeat("+current.service_columns+",1fr)");set(doc,".service-card","padding",px(current.service_card_padding));set(doc,".service-card","border-radius",px(current.service_card_radius));set(doc,".service-card","min-height",px(current.service_card_min_height));set(doc,".service-card","gap",px(current.service_card_gap));set(doc,".service-icon","width",px(current.service_icon_size));set(doc,".service-icon","height",px(current.service_icon_size));set(doc,".contact-section","padding-top",px(current.contact_section_padding));set(doc,".contact-section","padding-bottom",px(current.contact_section_padding));set(doc,".contact-box","padding",px(current.contact_padding));set(doc,".contact-box","gap",px(current.contact_gap));set(doc,".contact-box","border-radius",px(current.contact_radius));set(doc,".contact-link","min-height",px(current.contact_link_height));set(doc,".contact-link","padding-left",px(current.contact_link_padding));set(doc,".contact-link","padding-right",px(current.contact_link_padding));set(doc,".contact-content h2","font-size",px(current.contact_title_font_size));set(doc,".contact-content p","font-size",px(current.contact_text_font_size));set(doc,".site-footer","padding-top",px(current.footer_padding));set(doc,".site-footer","padding-bottom",px(current.footer_padding));
    let st=doc.getElementById("fkDesignRuntimeStyle");if(!st){st=doc.createElement("style");st.id="fkDesignRuntimeStyle";doc.head.appendChild(st);}st.textContent=`@media(max-width:1100px){.portfolio-slider{grid-template-columns:repeat(${current.portfolio_columns_tablet},1fr)!important}.hero-container{gap:${px(current.mobile_hero_gap)}!important}.hero-brand-main{font-size:${px(Math.min(current.mobile_brand_size,260))}!important}.hero-brand-name{font-size:${px(current.mobile_brand_name_size)}!important;letter-spacing:${px(current.mobile_brand_name_spacing)}!important}.hero-visual{min-height:${px(current.mobile_hero_visual_height)}!important}}@media(max-width:800px){.site-header{height:${px(current.mobile_header_height)}!important}.section-container,.header-container,.footer-container,.hero-container{width:calc(100% - ${px(current.mobile_side_padding*2)})!important}.hero-content{padding-top:${px(current.mobile_hero_padding_top)}!important;padding-bottom:${px(current.mobile_hero_padding_bottom)}!important}.hero-title{font-size:${px(current.mobile_hero_title_size)}!important}.hero-description{font-size:${px(current.mobile_hero_description_size)}!important}.hero-brand-main{font-size:${px(current.mobile_brand_size)}!important;letter-spacing:${px(current.mobile_brand_spacing)}!important}.hero-brand-name{font-size:${px(current.mobile_brand_name_size)}!important;letter-spacing:${px(current.mobile_brand_name_spacing)}!important}.portfolio-image{height:${px(current.mobile_portfolio_image_height)}!important}.contact-box{padding:${px(current.mobile_contact_padding)}!important}.primary-button,.secondary-button{height:${px(current.mobile_button_height)}!important}.hero-buttons{gap:${px(current.mobile_button_gap)}!important}.portfolio-section,.about-section,.services-section{padding-top:${px(current.mobile_section_padding)}!important;padding-bottom:${px(current.mobile_section_padding)}!important}}@media(max-width:500px){.hero-title{font-size:${px(current.mobile_hero_title_size_small)}!important}.hero-description{font-size:${px(current.mobile_hero_description_size_small)}!important}.portfolio-image{height:${px(current.mobile_portfolio_image_height_small)}!important}}`;
  }
  async function load(){if(!client)return;try{const {data}=await client.from("site_settings").select("setting_key,setting_value").like("setting_key","design_%");const s={};(data||[]).forEach(x=>s[x.setting_key.replace(/^design_/,'')]=parse(x.setting_value));apply(s);}catch(e){console.warn("Tasarım ayarları yüklenemedi",e);}}
  window.addEventListener("message",e=>{if(e.data?.type==="fk-design-preview"&&e.data.settings)apply(e.data.settings);});
  load();
})();
